CREATE TABLE `QNA` (
	`id`	BIGINT	NOT NULL,
	`project_id`	BIGINT	NOT NULL,
	`titme`	VARCHAR(100)	NOT NULL,
	`content`	TEXT	NOT NULL,
	`visibility`	BOOLEAN	NOT NULL,
	`answer`	TEXT	NULL,
	`created_at`	DATETIME	NOT NULL,
	`modified_At`	DATETIME	NULL,
	`id2`	BIGINT	NOT NULL,
	`role_id`	BIGINT	NOT NULL
);

CREATE TABLE `PURCHASE_CATEGORY` (
	`id`	BIGINT	NOT NULL,
	`name`	VARCHAR(100)	NOT NULL,
	`created_at`	DATETIME	NOT NULL,
	`modified_at`	DATETIME	NOT NULL,
	`type`	ENUM	NULL
);

CREATE TABLE `ALARM` (
	`id`	BIGINT	NOT NULL,
	`user_id`	BIGINT	NOT NULL,
	`status`	ENUM	NOT NULL	COMMENT '알림 상태',
	`content`	VARCHAR(100)	NOT NULL,
	`created_at`	DATETIME	NOT NULL,
	`modified_at`	DATETIME	NOT NULL
);

CREATE TABLE `ROLE` (
	`id`	BIGINT	NOT NULL,
	`name`	VARCHAR(50)	NOT NULL,
	`created_at`	DATETIME	NOT NULL,
	`modified_at`	DATETIME	NOT NULL
);

CREATE TABLE `PURCHASE` (
	`id`	BIGINT	NOT NULL,
	`project_id`	BIGINT	NOT NULL,
	`category_id`	BIGINT	NOT NULL,
	`git_address`	VARCHAR(255)	NOT NULL,
	`providing_method`	ENUM	NULL	COMMENT '다운로드 , 이메일',
	`average_delivery_time`	VARCHAR(255)	NULL,
	`file`	S3	NULL,
	`created_at`	DATETIME	NULL,
	`modified_at`	DATETIME	NULL
);

CREATE TABLE `OPTION` (
	`id`	BIGINT	NOT NULL,
	`purchase-id`	BIGINT	NOT NULL,
	`id2`	BIGINT	NOT NULL,
	`title`	VARCHAR(100)	NOT NULL,
	`reward_status`	ENUM	NOT NULL	COMMENT 'AVAILABLE (판매중) SOLD_OUT(품절) SCHEDULED ( 오픈예정) DISCONTINUED(판매중지)',
	`content`	VARCHAR(100)	NOT NULL,
	`price`	BIGINT	NOT NULL,
	`created_at`	DATETIME	NOT NULL,
	`modified_at`	DATETIME	NOT NULL
);

CREATE TABLE `USER_DONATION_PROJECTS` (
	`id`	BIGINT	NOT NULL,
	`user_id`	BIGINT	NOT NULL,
	`project_id`	BIGINT	NOT NULL,
	`price`	BIGINT	NULL,
	`created_at`	DATETIME	NOT NULL,
	`modified_at`	DATETIME	NOT NULL
);

CREATE TABLE `PROJECT_IMAGE` (
	`id`	BIGINT	NOT NULL,
	`project_id`	BIGINT	NOT NULL,
	`image_url`	TEXT	NOT NULL,
	`image_order`	BIGINT	NULL,
	`storedFileName`	VARCHAR(255)	NOT NULL,
	`originalFilename`	VARCHAR(255)	NOT NULL,
	`created_at`	DATETIME	NOT NULL,
	`modified_at`	DATETIME	NOT NULL
);

CREATE TABLE `SUB_CATEGORY` (
	`id`	BIGINT	NOT NULL,
	`name`	VARCHAR(100)	NOT NULL,
	`created_at`	DATETIME	NOT NULL,
	`modified_at`	DATETIME	NOT NULL,
	`type`	ENUM	NULL
);

CREATE TABLE `PROJECT_SUB_CATEGORY` (
	`id`	BIGINT	NOT NULL,
	`sub_project_id`	BIGINT	NOT NULL,
	`donation_id`	BIGINT	NOT NULL
);

CREATE TABLE `USER_PURCHASE_PROJECTS` (
	`id`	BIGINT	NOT NULL,
	`user_id`	BIGINT	NOT NULL,
	`project_id`	BIGINT	NOT NULL,
	`download_expire_at`	DATETIME	NULL	COMMENT '생성된 내역 + 7일 하면 될듯',
	`download_count`	VARCHAR(255)	NULL	COMMENT '프로젝트 최대 다운로드 횟수 필요할듯',
	`created_at`	DATETIME	NOT NULL,
	`modified_at`	DATETIME	NOT NULL
);

CREATE TABLE `FOLLOW` (
	`id`	BIGINT	NOT NULL,
	`follower_id`	BIGINT	NOT NULL	COMMENT '로그인 한 사람 아이디 = 팔로우 하려는 사람',
	`following_id`	BIGINT	NOT NULL	COMMENT '팔로우 당하는 사람 아이디',
	`created_at`	DATETIME	NOT NULL,
	`modifed_at`	DATETIME	NOT NULL
);

CREATE TABLE `NOTICES` (
	`id`	BIGINT	NOT NULL,
	`project_id`	BIGINT	NOT NULL,
	`title`	VARCHAR(100)	NOT NULL,
	`content`	TEXT	NOT NULL,
	`created_at`	DATETIME	NOT NULL,
	`modified_at`	DATETIME	NOT NULL
);

CREATE TABLE `MAIN_CATEGORY` (
	`id`	BIGINT	NOT NULL,
	`name`	VARCHAR(100)	NOT NULL,
	`created_at`	DATETIME	NOT NULL,
	`modified_at`	DATETIME	NOT NULL,
	`type`	ENUM	NULL
);

CREATE TABLE `SECTION` (
	`Key`	VARCHAR(255)	NOT NULL,
	`project_id`	BIGINT	NOT NULL
);

CREATE TABLE `SECTION_IMAGE` (
	`section_id`	VARCHAR(255)	NOT NULL	COMMENT '추가 기능',
	`Key`	VARCHAR(255)	NOT NULL,
	`project_id`	BIGINT	NOT NULL
);

CREATE TABLE `DONATION` (
	`id`	BIGINT	NOT NULL,
	`project_id`	BIGINT	NOT NULL,
	`main_category_id`	BIGINT	NOT NULL,
	`price_coal`	BIGINT	NULL,
	`start_date`	DATETIME	NOT NULL,
	`end_date`	DATETIME	NULL	COMMENT '최소 30일, 최대 100일',
	`git_address`	VARCHAR(255)	NULL,
	`deploy_address`	VARCHAR(255)	NOT NULL,
	`created_at`	DATETIME	NOT NULL,
	`modified_at`	DATETIME	NOT NULL
);

CREATE TABLE `REVIEWS` (
	`id`	BIGINT	NOT NULL,
	`user_id`	BIGINT	NOT NULL,
	`purchase_id`	BIGINT	NOT NULL,
	`id2`	BIGINT	NOT NULL,
	`content`	TEXT	NOT NULL,
	`rating`	FLOAT	NOT NULL,
	`created_at`	DATETIME	NOT NULL,
	`modified_At`	DATETIME	NOT NULL
);

CREATE TABLE `pricing_plan` (
	`id`	BIGINT	NOT NULL,
	`name`	VARCHAR(10)	NOT NULL,
	`platform_fee`	BIGINT	NOT NULL	COMMENT '플랫폼 운영사 수수료',
	`payment_fee`	BIGINT	NOT NULL	COMMENT '결제 처리(PG사 등) 수수료',
	`created_at`	DATETIME	NOT NULL,
	`modified_at`	DATETIME	NOT NULL
);

CREATE TABLE `LIKE` (
	`id`	BIGINT	NOT NULL,
	`user_id`	BIGINT	NOT NULL,
	`project_id`	BIGINT	NOT NULL,
	`created_at`	DATETIME	NOT NULL,
	`modified_at`	DATETIME	NOT NULL
);

CREATE TABLE `PROJECT` (
	`id`	BIGINT	NOT NULL,
	`user_id`	BIGINT	NOT NULL,
	`pricing_plan_id`	BIGINT	NOT NULL,
	`title`	VARCHAR(100)	NOT NULL,
	`introduce`	VARCHAR(255)	NOT NULL,
	`content`	TEXT	NOT NULL,
	`status`	ENUM	NOT NULL	COMMENT '프로젝트 상태 (모집중, 완료 , 심사중 등)',
	`project_type`	ENUM	NOT NULL	COMMENT '창작물 / 개발물',
	`modified_at`	DATETIME	NOT NULL,
	`Field`	VARCHAR(255)	NULL
);

CREATE TABLE `USER` (
	`id`	BIGINT	NOT NULL,
	`role_id`	BIGINT	NOT NULL,
	`name`	VARCHAR(10)	NOT NULL,
	`email`	VARCHAR(100)	NOT NULL,
	`phone_number`	VARCHAR(255)	NOT NULL,
	`account`	VARCHAR(255)	NULL,
	`bank`	VARCHAR(50)	NULL,
	`introduce`	VARCHAR(255)	NULL,
	`portfolio`	VARCHAR(255)	NULL,
	`image`	VARCHAR(255)	NOT NULL,
	`sso_provider`	VARCHAR(100)	NULL	COMMENT '카카오 깃허브등',
	`sso_id`	VARCHAR(100)	NULL,
	`refresh_token`	VARCHAR(255)	NULL,
	`user_active`	ENUM	NULL	COMMENT '정지, 활성,  신고중',
	`created_at`	DATETIME	NOT NULL,
	`modified_At`	DATETIME	NOT NULL
);

ALTER TABLE `QNA` ADD CONSTRAINT `PK_QNA` PRIMARY KEY (
	`id`,
	`project_id`
);

ALTER TABLE `PURCHASE_CATEGORY` ADD CONSTRAINT `PK_PURCHASE_CATEGORY` PRIMARY KEY (
	`id`
);

ALTER TABLE `ALARM` ADD CONSTRAINT `PK_ALARM` PRIMARY KEY (
	`id`,
	`user_id`
);

ALTER TABLE `ROLE` ADD CONSTRAINT `PK_ROLE` PRIMARY KEY (
	`id`
);

ALTER TABLE `PURCHASE` ADD CONSTRAINT `PK_PURCHASE` PRIMARY KEY (
	`id`,
	`project_id`,
	`category_id`
);

ALTER TABLE `OPTION` ADD CONSTRAINT `PK_OPTION` PRIMARY KEY (
	`id`,
	`purchase-id`,
	`id2`
);

ALTER TABLE `USER_DONATION_PROJECTS` ADD CONSTRAINT `PK_USER_DONATION_PROJECTS` PRIMARY KEY (
	`id`,
	`user_id`,
	`project_id`
);

ALTER TABLE `PROJECT_IMAGE` ADD CONSTRAINT `PK_PROJECT_IMAGE` PRIMARY KEY (
	`id`,
	`project_id`
);

ALTER TABLE `SUB_CATEGORY` ADD CONSTRAINT `PK_SUB_CATEGORY` PRIMARY KEY (
	`id`
);

ALTER TABLE `PROJECT_SUB_CATEGORY` ADD CONSTRAINT `PK_PROJECT_SUB_CATEGORY` PRIMARY KEY (
	`id`,
	`sub_project_id`,
	`donation_id`
);

ALTER TABLE `USER_PURCHASE_PROJECTS` ADD CONSTRAINT `PK_USER_PURCHASE_PROJECTS` PRIMARY KEY (
	`id`,
	`user_id`,
	`project_id`
);

ALTER TABLE `FOLLOW` ADD CONSTRAINT `PK_FOLLOW` PRIMARY KEY (
	`id`
);

ALTER TABLE `NOTICES` ADD CONSTRAINT `PK_NOTICES` PRIMARY KEY (
	`id`,
	`project_id`
);

ALTER TABLE `MAIN_CATEGORY` ADD CONSTRAINT `PK_MAIN_CATEGORY` PRIMARY KEY (
	`id`
);

ALTER TABLE `SECTION` ADD CONSTRAINT `PK_SECTION` PRIMARY KEY (
	`Key`,
	`project_id`
);

ALTER TABLE `SECTION_IMAGE` ADD CONSTRAINT `PK_SECTION_IMAGE` PRIMARY KEY (
	`section_id`,
	`Key`,
	`project_id`
);

ALTER TABLE `DONATION` ADD CONSTRAINT `PK_DONATION` PRIMARY KEY (
	`id`,
	`project_id`,
	`main_category_id`
);

ALTER TABLE `REVIEWS` ADD CONSTRAINT `PK_REVIEWS` PRIMARY KEY (
	`id`,
	`user_id`,
	`purchase_id`,
	`id2`
);

ALTER TABLE `pricing_plan` ADD CONSTRAINT `PK_PRICING_PLAN` PRIMARY KEY (
	`id`
);

ALTER TABLE `LIKE` ADD CONSTRAINT `PK_LIKE` PRIMARY KEY (
	`id`,
	`user_id`,
	`project_id`
);

ALTER TABLE `PROJECT` ADD CONSTRAINT `PK_PROJECT` PRIMARY KEY (
	`id`,
	`user_id`,
	`pricing_plan_id`
);

ALTER TABLE `USER` ADD CONSTRAINT `PK_USER` PRIMARY KEY (
	`id`,
	`role_id`
);

ALTER TABLE `QNA` ADD CONSTRAINT `FK_PROJECT_TO_QNA_1` FOREIGN KEY (
	`project_id`
)
REFERENCES `PROJECT` (
	`id`
);

ALTER TABLE `ALARM` ADD CONSTRAINT `FK_USER_TO_ALARM_1` FOREIGN KEY (
	`user_id`
)
REFERENCES `USER` (
	`id`
);

ALTER TABLE `PURCHASE` ADD CONSTRAINT `FK_PROJECT_TO_PURCHASE_1` FOREIGN KEY (
	`project_id`
)
REFERENCES `PROJECT` (
	`id`
);

ALTER TABLE `PURCHASE` ADD CONSTRAINT `FK_PURCHASE_CATEGORY_TO_PURCHASE_1` FOREIGN KEY (
	`category_id`
)
REFERENCES `PURCHASE_CATEGORY` (
	`id`
);

ALTER TABLE `OPTION` ADD CONSTRAINT `FK_PURCHASE_TO_OPTION_1` FOREIGN KEY (
	`purchase-id`
)
REFERENCES `PURCHASE` (
	`id`
);

ALTER TABLE `OPTION` ADD CONSTRAINT `FK_PURCHASE_TO_OPTION_2` FOREIGN KEY (
	`id2`
)
REFERENCES `PURCHASE` (
	`category_id`
);

ALTER TABLE `USER_DONATION_PROJECTS` ADD CONSTRAINT `FK_USER_TO_USER_DONATION_PROJECTS_1` FOREIGN KEY (
	`user_id`
)
REFERENCES `USER` (
	`id`
);

ALTER TABLE `USER_DONATION_PROJECTS` ADD CONSTRAINT `FK_PROJECT_TO_USER_DONATION_PROJECTS_1` FOREIGN KEY (
	`project_id`
)
REFERENCES `PROJECT` (
	`id`
);

ALTER TABLE `PROJECT_IMAGE` ADD CONSTRAINT `FK_PROJECT_TO_PROJECT_IMAGE_1` FOREIGN KEY (
	`project_id`
)
REFERENCES `PROJECT` (
	`id`
);

ALTER TABLE `PROJECT_SUB_CATEGORY` ADD CONSTRAINT `FK_SUB_CATEGORY_TO_PROJECT_SUB_CATEGORY_1` FOREIGN KEY (
	`sub_project_id`
)
REFERENCES `SUB_CATEGORY` (
	`id`
);

ALTER TABLE `PROJECT_SUB_CATEGORY` ADD CONSTRAINT `FK_DONATION_TO_PROJECT_SUB_CATEGORY_1` FOREIGN KEY (
	`donation_id`
)
REFERENCES `DONATION` (
	`id`
);

ALTER TABLE `USER_PURCHASE_PROJECTS` ADD CONSTRAINT `FK_USER_TO_USER_PURCHASE_PROJECTS_1` FOREIGN KEY (
	`user_id`
)
REFERENCES `USER` (
	`id`
);

ALTER TABLE `USER_PURCHASE_PROJECTS` ADD CONSTRAINT `FK_PROJECT_TO_USER_PURCHASE_PROJECTS_1` FOREIGN KEY (
	`project_id`
)
REFERENCES `PROJECT` (
	`id`
);

ALTER TABLE `NOTICES` ADD CONSTRAINT `FK_PROJECT_TO_NOTICES_1` FOREIGN KEY (
	`project_id`
)
REFERENCES `PROJECT` (
	`id`
);

ALTER TABLE `SECTION` ADD CONSTRAINT `FK_PROJECT_TO_SECTION_1` FOREIGN KEY (
	`project_id`
)
REFERENCES `PROJECT` (
	`id`
);

ALTER TABLE `SECTION_IMAGE` ADD CONSTRAINT `FK_SECTION_TO_SECTION_IMAGE_1` FOREIGN KEY (
	`Key`
)
REFERENCES `SECTION` (
	`Key`
);

ALTER TABLE `SECTION_IMAGE` ADD CONSTRAINT `FK_SECTION_TO_SECTION_IMAGE_2` FOREIGN KEY (
	`project_id`
)
REFERENCES `SECTION` (
	`project_id`
);

ALTER TABLE `DONATION` ADD CONSTRAINT `FK_PROJECT_TO_DONATION_1` FOREIGN KEY (
	`project_id`
)
REFERENCES `PROJECT` (
	`id`
);

ALTER TABLE `DONATION` ADD CONSTRAINT `FK_MAIN_CATEGORY_TO_DONATION_1` FOREIGN KEY (
	`main_category_id`
)
REFERENCES `MAIN_CATEGORY` (
	`id`
);

ALTER TABLE `REVIEWS` ADD CONSTRAINT `FK_USER_TO_REVIEWS_1` FOREIGN KEY (
	`user_id`
)
REFERENCES `USER` (
	`id`
);

ALTER TABLE `REVIEWS` ADD CONSTRAINT `FK_PURCHASE_TO_REVIEWS_1` FOREIGN KEY (
	`purchase_id`
)
REFERENCES `PURCHASE` (
	`id`
);

ALTER TABLE `REVIEWS` ADD CONSTRAINT `FK_PURCHASE_TO_REVIEWS_2` FOREIGN KEY (
	`id2`
)
REFERENCES `PURCHASE` (
	`category_id`
);

ALTER TABLE `LIKE` ADD CONSTRAINT `FK_USER_TO_LIKE_1` FOREIGN KEY (
	`user_id`
)
REFERENCES `USER` (
	`id`
);

ALTER TABLE `LIKE` ADD CONSTRAINT `FK_PROJECT_TO_LIKE_1` FOREIGN KEY (
	`project_id`
)
REFERENCES `PROJECT` (
	`id`
);

ALTER TABLE `PROJECT` ADD CONSTRAINT `FK_USER_TO_PROJECT_1` FOREIGN KEY (
	`user_id`
)
REFERENCES `USER` (
	`id`
);

ALTER TABLE `PROJECT` ADD CONSTRAINT `FK_pricing_plan_TO_PROJECT_1` FOREIGN KEY (
	`pricing_plan_id`
)
REFERENCES `pricing_plan` (
	`id`
);

ALTER TABLE `USER` ADD CONSTRAINT `FK_ROLE_TO_USER_1` FOREIGN KEY (
	`role_id`
)
REFERENCES `ROLE` (
	`id`
);

