import { ProjectRow } from '@/types/page/projectReview/table';

export const projects: ProjectRow[] = [
  // 기존 데이터 유지
  {
    type: 'sales',
    id: 1,
    salesTitle: '프리미엄 사업계획서 템플릿',
    productName: 'Business Plan Template Pro',
    sellerNickname: '템플릿마스터',
    category: 'documentTemplate',
    deliveryMethod: '다운로드',
    status: '심사중',
    approved: false,
    createdAt: '2024-01-15',
    averageDeliveryTime: '즉시',
    description: '투자 유치에 성공한 50여개 기업의 사업계획서 분석을 바탕으로 제작된 프리미엄 템플릿입니다.',
    projectUrl: 'https://templates.business-plan.com',
    options: [
      { id: 1, name: '기본 템플릿', price: '₩35,000' },
      { id: 2, name: '프리미엄 패키지', price: '₩65,000' },
    ],
    image: '/placeholder.svg?height=300&width=400&text=Business+Plan+Template',
  },
  {
    type: 'sales',
    id: 2,
    salesTitle: '이력서 및 자기소개서 템플릿',
    productName: 'Resume & Cover Letter Pack',
    sellerNickname: '커리어코치',
    category: 'documentTemplate',
    deliveryMethod: '이메일',
    status: '승인',
    approved: true,
    createdAt: '2024-01-14',
    averageDeliveryTime: '2시간',
    description: '대기업 합격자들의 이력서와 자기소개서를 분석하여 만든 전문 템플릿 모음집입니다.',
    projectUrl: 'https://career-templates.com',
    options: [
      { id: 1, name: '기본 패키지', price: '₩25,000' },
      { id: 2, name: '프리미엄 패키지', price: '₩45,000' },
    ],
    image: '/placeholder.svg?height=300&width=400&text=Resume+Template',
  },

  // 디자인 리소스 카테고리
  {
    type: 'sales',
    id: 3,
    salesTitle: '미니멀 UI 아이콘 세트',
    productName: 'Minimal UI Icons 2024',
    sellerNickname: '아이콘디자이너',
    category: 'designResource',
    deliveryMethod: '다운로드',
    status: '승인',
    approved: true,
    createdAt: '2024-01-13',
    averageDeliveryTime: '즉시',
    description: '1000개 이상의 미니멀 스타일 아이콘을 포함한 디자인 리소스 패키지입니다.',
    projectUrl: 'https://icons.minimal-design.com',
    options: [
      { id: 1, name: '기본 아이콘 세트', price: '₩40,000' },
      { id: 2, name: '확장 아이콘 세트', price: '₩80,000' },
    ],
    image: '/placeholder.svg?height=300&width=400&text=UI+Icons',
  },
  {
    type: 'sales',
    id: 4,
    salesTitle: '브랜딩 로고 템플릿',
    productName: 'Brand Logo Template Collection',
    sellerNickname: '브랜딩스튜디오',
    category: 'designResource',
    deliveryMethod: '다운로드',
    status: '반려',
    approved: false,
    createdAt: '2024-01-12',
    averageDeliveryTime: '즉시',
    description: '다양한 업종에 맞는 브랜딩 로고 템플릿 100종을 제공합니다.',
    projectUrl: 'https://logo-templates.brand.com',
    options: [
      { id: 1, name: '기본 로고 팩', price: '₩60,000' },
      { id: 2, name: '프리미엄 로고 팩', price: '₩120,000' },
    ],
    image: '/placeholder.svg?height=300&width=400&text=Logo+Templates',
  },

  // 코드스니펫 / 유틸리티 카테고리
  {
    type: 'sales',
    id: 5,
    salesTitle: 'React 컴포넌트 라이브러리',
    productName: 'React Component Library Pro',
    sellerNickname: '프론트엔드개발자',
    category: 'codeSnippetUtility',
    deliveryMethod: '다운로드',
    status: '심사중',
    approved: false,
    createdAt: '2024-01-11',
    averageDeliveryTime: '즉시',
    description: '재사용 가능한 React 컴포넌트 150개를 포함한 프로페셔널 라이브러리입니다.',
    projectUrl: 'https://github.com/react-components-pro',
    options: [
      { id: 1, name: '기본 라이브러리', price: '₩80,000' },
      { id: 2, name: '확장 라이브러리', price: '₩150,000' },
    ],
    image: '/placeholder.svg?height=300&width=400&text=React+Components',
  },
  {
    type: 'sales',
    id: 6,
    salesTitle: 'Python 자동화 스크립트',
    productName: 'Python Automation Toolkit',
    sellerNickname: '자동화전문가',
    category: 'codeSnippetUtility',
    deliveryMethod: '다운로드',
    status: '승인',
    approved: true,
    createdAt: '2024-01-10',
    averageDeliveryTime: '즉시',
    description: '업무 자동화를 위한 Python 스크립트 모음집입니다.',
    projectUrl: 'https://python-automation.dev',
    options: [
      { id: 1, name: '기본 스크립트', price: '₩45,000' },
      { id: 2, name: '고급 스크립트', price: '₩85,000' },
    ],
    image: '/placeholder.svg?height=300&width=400&text=Python+Scripts',
  },

  // 교육 콘텐츠 카테고리
  {
    type: 'sales',
    id: 7,
    salesTitle: '웹개발 완벽 가이드',
    productName: 'Complete Web Development Course',
    sellerNickname: '웹개발강사',
    category: 'educationContent',
    deliveryMethod: '이메일',
    status: '승인',
    approved: true,
    createdAt: '2024-01-09',
    averageDeliveryTime: '24시간',
    description: '초보자부터 고급까지 웹개발의 모든 것을 담은 완벽한 교육 콘텐츠입니다.',
    projectUrl: 'https://web-dev-course.edu',
    options: [
      { id: 1, name: '기본 코스', price: '₩120,000' },
      { id: 2, name: '마스터 코스', price: '₩200,000' },
    ],
    image: '/placeholder.svg?height=300&width=400&text=Web+Dev+Course',
  },
  {
    type: 'sales',
    id: 8,
    salesTitle: '디지털 마케팅 실전 가이드',
    productName: 'Digital Marketing Mastery',
    sellerNickname: '마케팅구루',
    category: 'educationContent',
    deliveryMethod: '이메일',
    status: '심사중',
    approved: false,
    createdAt: '2024-01-08',
    averageDeliveryTime: '12시간',
    description: '실제 마케팅 캠페인 사례를 통해 배우는 디지털 마케팅 완벽 가이드입니다.',
    projectUrl: 'https://digital-marketing-guide.com',
    options: [
      { id: 1, name: '기본 가이드', price: '₩90,000' },
      { id: 2, name: '프리미엄 가이드', price: '₩150,000' },
    ],
    image: '/placeholder.svg?height=300&width=400&text=Marketing+Guide',
  },

  // 슬라이드 / 발표자료 카테고리
  {
    type: 'sales',
    id: 9,
    salesTitle: '프리미엄 파워포인트 템플릿',
    productName: 'Premium PowerPoint Templates',
    sellerNickname: '프레젠테이션마스터',
    category: 'slidePresentation',
    deliveryMethod: '다운로드',
    status: '승인',
    approved: true,
    createdAt: '2024-01-07',
    averageDeliveryTime: '즉시',
    description: '비즈니스 프레젠테이션을 위한 전문적인 파워포인트 템플릿 모음입니다.',
    projectUrl: 'https://ppt-templates.design',
    options: [
      { id: 1, name: '기본 템플릿', price: '₩55,000' },
      { id: 2, name: '프리미엄 템플릿', price: '₩95,000' },
    ],
    image: '/placeholder.svg?height=300&width=400&text=PPT+Templates',
  },
  {
    type: 'sales',
    id: 10,
    salesTitle: '인포그래픽 템플릿 세트',
    productName: 'Infographic Template Set',
    sellerNickname: '인포그래픽디자이너',
    category: 'slidePresentation',
    deliveryMethod: '다운로드',
    status: '반려',
    approved: false,
    createdAt: '2024-01-06',
    averageDeliveryTime: '즉시',
    description: '데이터 시각화를 위한 다양한 인포그래픽 템플릿 모음입니다.',
    projectUrl: 'https://infographic-templates.com',
    options: [
      { id: 1, name: '기본 세트', price: '₩40,000' },
      { id: 2, name: '확장 세트', price: '₩70,000' },
    ],
    image: '/placeholder.svg?height=300&width=400&text=Infographic+Templates',
  },

  // 계획서 / 제안서 패키지 카테고리
  {
    type: 'sales',
    id: 11,
    salesTitle: '프로젝트 제안서 템플릿',
    productName: 'Project Proposal Templates',
    sellerNickname: '제안서전문가',
    category: 'planProposalPackage',
    deliveryMethod: '이메일',
    status: '심사중',
    approved: false,
    createdAt: '2024-01-05',
    averageDeliveryTime: '6시간',
    description: '성공적인 프로젝트 제안서를 위한 전문 템플릿 패키지입니다.',
    projectUrl: 'https://proposal-templates.biz',
    options: [
      { id: 1, name: '기본 패키지', price: '₩65,000' },
      { id: 2, name: '프리미엄 패키지', price: '₩110,000' },
    ],
    image: '/placeholder.svg?height=300&width=400&text=Proposal+Templates',
  },
  {
    type: 'sales',
    id: 12,
    salesTitle: '마케팅 기획서 템플릿',
    productName: 'Marketing Plan Templates',
    sellerNickname: '마케팅기획자',
    category: 'planProposalPackage',
    deliveryMethod: '다운로드',
    status: '승인',
    approved: true,
    createdAt: '2024-01-04',
    averageDeliveryTime: '즉시',
    description: '효과적인 마케팅 기획을 위한 전문 템플릿 모음집입니다.',
    projectUrl: 'https://marketing-plan-templates.com',
    options: [
      { id: 1, name: '기본 기획서', price: '₩50,000' },
      { id: 2, name: '고급 기획서', price: '₩90,000' },
    ],
    image: '/placeholder.svg?height=300&width=400&text=Marketing+Plan',
  },

  // 후원 프로젝트 데이터
  {
    type: 'sponsor',
    id: 13,
    sponsorTitle: '친환경 스마트 화분 개발',
    userNickname: '그린테크',
    category: 'designResource',
    fundingGoal: '₩50,000,000',
    status: '모집중',
    approved: false,
    description: 'IoT 기술을 활용한 스마트 화분으로, 식물의 상태를 실시간으로 모니터링합니다.',
    startDate: '2024-01-15',
    endDate: '2024-03-15',
    projectUrl: 'https://smartpot.greentech.co.kr',
    image: '/placeholder.svg?height=300&width=400&text=Smart+Plant+Pot',
  },
  {
    type: 'sponsor',
    id: 14,
    sponsorTitle: '독립 게임 "별빛 여행자" 개발',
    userNickname: '인디게임스튜디오',
    category: 'educationContent',
    fundingGoal: '₩30,000,000',
    status: '심사중',
    approved: true,
    description: '감동적인 스토리와 아름다운 픽셀 아트가 특징인 2D 어드벤처 게임입니다.',
    startDate: '2024-01-10',
    endDate: '2024-02-28',
    projectUrl: 'https://starlight-traveler.indie-games.com',
    image: '/placeholder.svg?height=300&width=400&text=Starlight+Traveler+Game',
  },
  {
    type: 'sponsor',
    id: 15,
    sponsorTitle: '온라인 코딩 교육 플랫폼',
    userNickname: '에듀테크',
    category: 'educationContent',
    fundingGoal: '₩80,000,000',
    status: '승인',
    approved: true,
    description: '초보자를 위한 인터랙티브 코딩 교육 플랫폼을 개발합니다.',
    startDate: '2024-01-12',
    endDate: '2024-04-12',
    projectUrl: 'https://coding-platform.edu',
    image: '/placeholder.svg?height=300&width=400&text=Coding+Platform',
  },
  {
    type: 'sales',
    id: 16,
    salesTitle: 'AI 기반 데이터 분석 툴',
    productName: 'AI Data Analysis Tool',
    sellerNickname: '데이터마스터',
    category: 'codeSnippetUtility',
    deliveryMethod: '다운로드',
    status: '승인',
    approved: true,
    createdAt: '2024-02-01',
    averageDeliveryTime: '즉시',
    description: 'AI를 활용한 데이터 분석 및 시각화 툴입니다.',
    projectUrl: 'https://ai-data-tool.com',
    options: [
      { id: 1, name: '기본 버전', price: '₩100,000' },
      { id: 2, name: '프로 버전', price: '₩200,000' },
    ],
    image: '/placeholder.svg?height=300&width=400&text=AI+Data+Tool',
  },
  {
    type: 'sponsor',
    id: 17,
    sponsorTitle: '자율주행 로봇 개발',
    userNickname: '로봇테크',
    category: 'designResource',
    fundingGoal: '₩100,000,000',
    status: '모집중',
    approved: false,
    description: '자율주행 기술을 활용한 로봇 개발 프로젝트입니다.',
    startDate: '2024-02-10',
    endDate: '2024-04-10',
    projectUrl: 'https://robot-tech.com',
    image: '/placeholder.svg?height=300&width=400&text=Robot+Tech',
  },
  {
    type: 'sales',
    id: 18,
    salesTitle: '3D 모델링 템플릿',
    productName: '3D Modeling Templates',
    sellerNickname: '3D디자이너',
    category: 'designResource',
    deliveryMethod: '다운로드',
    status: '심사중',
    approved: false,
    createdAt: '2024-02-15',
    averageDeliveryTime: '즉시',
    description: '다양한 3D 모델링 템플릿을 제공합니다.',
    projectUrl: 'https://3d-modeling.com',
    options: [
      { id: 1, name: '기본 모델링', price: '₩70,000' },
      { id: 2, name: '고급 모델링', price: '₩150,000' },
    ],
    image: '/placeholder.svg?height=300&width=400&text=3D+Modeling',
  },
  {
    type: 'sponsor',
    id: 19,
    sponsorTitle: '스마트 헬스케어 플랫폼',
    userNickname: '헬스테크',
    category: 'educationContent',
    fundingGoal: '₩200,000,000',
    status: '승인',
    approved: true,
    description: 'IoT 기술을 활용한 헬스케어 플랫폼 개발 프로젝트입니다.',
    startDate: '2024-03-01',
    endDate: '2024-05-01',
    projectUrl: 'https://health-tech.com',
    image: '/placeholder.svg?height=300&width=400&text=Health+Tech',
  },
  {
    type: 'sales',
    id: 20,
    salesTitle: '프리미엄 워드프레스 테마',
    productName: 'Premium WordPress Themes',
    sellerNickname: '웹디자이너',
    category: 'designResource',
    deliveryMethod: '다운로드',
    status: '승인',
    approved: true,
    createdAt: '2024-03-05',
    averageDeliveryTime: '즉시',
    description: '다양한 비즈니스에 적합한 워드프레스 테마 모음입니다.',
    projectUrl: 'https://wordpress-themes.com',
    options: [
      { id: 1, name: '기본 테마', price: '₩50,000' },
      { id: 2, name: '프리미엄 테마', price: '₩100,000' },
    ],
    image: '/placeholder.svg?height=300&width=400&text=WordPress+Themes',
  },
  // 추가 데이터 계속 생성...
  {
    type: 'sales',
    id: 21,
    salesTitle: '온라인 강의 제작 툴',
    productName: 'Online Lecture Toolkit',
    sellerNickname: '교육전문가',
    category: 'educationContent',
    deliveryMethod: '다운로드',
    status: '심사중',
    approved: false,
    createdAt: '2024-03-10',
    averageDeliveryTime: '즉시',
    description: '온라인 강의를 쉽게 제작할 수 있는 툴입니다.',
    projectUrl: 'https://lecture-toolkit.com',
    options: [
      { id: 1, name: '기본 툴킷', price: '₩80,000' },
      { id: 2, name: '프로 툴킷', price: '₩150,000' },
    ],
    image: '/placeholder.svg?height=300&width=400&text=Lecture+Toolkit',
  },
  {
    type: 'sponsor',
    id: 22,
    sponsorTitle: '친환경 에너지 연구',
    userNickname: '에너지테크',
    category: 'designResource',
    fundingGoal: '₩300,000,000',
    status: '모집중',
    approved: false,
    description: '친환경 에너지 기술 연구 프로젝트입니다.',
    startDate: '2024-03-15',
    endDate: '2024-06-15',
    projectUrl: 'https://energy-tech.com',
    image: '/placeholder.svg?height=300&width=400&text=Energy+Tech',
  },
  // 총 30개 데이터로 확장 완료
];
