export const members = [
  {
    id: 1,
    nickname: '김창작',
    email: 'creator@example.com',
    joinDate: '2024-01-10',
    lastActivity: '2시간 전',
    category: '프로젝트 0개',
    fundingAmount: 95200,
    status: '신규회원',
    accountStatus: '정상',
    level: '일반',
    projectCount: 0,
    totalAmount: 120000,
    paymentStatus: '신고접수',
    approvalStatus: '높음',
    memberStatus: '검토중',
    location: '창작자',
  },
  {
    id: 2,
    nickname: '이후원',
    email: 'supporter@example.com',
    joinDate: '2024-01-08',
    lastActivity: '1시간 전',
    category: '프로젝트 0개',
    fundingAmount: 650000,
    status: '신규회원',
    accountStatus: '정상',
    level: '일반',
    projectCount: 1,
    totalAmount: 120000,
    paymentStatus: '신고접수',
    approvalStatus: '높음',
    memberStatus: '검토중',
    location: '후원자',
  },
  {
    id: 3,
    nickname: '박신고',
    email: 'reported@example.com',
    joinDate: '2024-01-05',
    lastActivity: '3시간 전',
    category: '프로젝트 1개',
    fundingAmount: 120000,
    status: '검토중',
    accountStatus: '신고접수',
    level: '높음',
    projectCount: 1,
    totalAmount: 120000,
    paymentStatus: '신고접수',
    approvalStatus: '높음',
    memberStatus: '검토중',
    location: '창작자',
  },
  {
    id: 4,
    nickname: '최정지',
    email: 'suspended@example.com',
    joinDate: '2023-12-20',
    lastActivity: '1주일 전',
    category: '프로젝트 0개',
    fundingAmount: 0,
    status: '이용정지',
    accountStatus: '이용정지',
    level: '높음',
    projectCount: 0,
    totalAmount: 120000,
    paymentStatus: '신고접수',
    approvalStatus: '높음',
    memberStatus: '검토중',
    location: '후원자',
  },
  {
    id: 5,
    nickname: '오활동',
    email: 'active@example.com',
    joinDate: '2024-02-01',
    lastActivity: '방금 전',
    category: '프로젝트 2개',
    fundingAmount: 300000,
    status: '활동중',
    accountStatus: '정상',
    level: '높음',
    projectCount: 2,
    totalAmount: 500000,
    paymentStatus: '정상',
    approvalStatus: '높음',
    memberStatus: '승인됨',
    location: '창작자',
  },
  {
    id: 6,
    nickname: '육보류',
    email: 'pending@example.com',
    joinDate: '2024-01-15',
    lastActivity: '5분 전',
    category: '프로젝트 1개',
    fundingAmount: 80000,
    status: '보류',
    accountStatus: '정상',
    level: '일반',
    projectCount: 1,
    totalAmount: 80000,
    paymentStatus: '보류',
    approvalStatus: '보통',
    memberStatus: '검토중',
    location: '창작자',
  },
  {
    id: 7,
    nickname: '칠후원',
    email: 'vip-supporter@example.com',
    joinDate: '2024-02-10',
    lastActivity: '30분 전',
    category: '프로젝트 5개',
    fundingAmount: 2000000,
    status: 'VIP',
    accountStatus: '정상',
    level: '최상',
    projectCount: 5,
    totalAmount: 2000000,
    paymentStatus: '정상',
    approvalStatus: '매우 높음',
    memberStatus: '승인됨',
    location: '후원자',
  },
  {
    id: 8,
    nickname: '팔창작',
    email: 'creative@example.com',
    joinDate: '2024-01-20',
    lastActivity: '2일 전',
    category: '프로젝트 3개',
    fundingAmount: 450000,
    status: '활동중',
    accountStatus: '정상',
    level: '높음',
    projectCount: 3,
    totalAmount: 600000,
    paymentStatus: '정상',
    approvalStatus: '높음',
    memberStatus: '승인됨',
    location: '창작자',
  },
  {
    id: 9,
    nickname: '구정지',
    email: 'banned@example.com',
    joinDate: '2023-11-15',
    lastActivity: '1달 전',
    category: '프로젝트 0개',
    fundingAmount: 0,
    status: '이용정지',
    accountStatus: '이용정지',
    level: '낮음',
    projectCount: 0,
    totalAmount: 0,
    paymentStatus: '차단',
    approvalStatus: '낮음',
    memberStatus: '차단됨',
    location: '후원자',
  },
  {
    id: 10,
    nickname: '십활발',
    email: 'activeuser@example.com',
    joinDate: '2024-02-15',
    lastActivity: '10분 전',
    category: '프로젝트 4개',
    fundingAmount: 900000,
    status: '활동중',
    accountStatus: '정상',
    level: '높음',
    projectCount: 4,
    totalAmount: 1000000,
    paymentStatus: '정상',
    approvalStatus: '높음',
    memberStatus: '승인됨',
    location: '창작자',
  },
];
