export const members = [
  {
    id: 1,
    nickname: '김창작',
    email: 'creator@example.com',
    joinDate: '2024-01-10',
    lastActivity: '2시간 전',
    category: '프로젝트 0개',
    fundingAmount: 95_200,
    status: '신규회원',
    accountStatus: '정상',
    level: '일반',
    projectCount: 0,
    totalAmount: 120_000,
    paymentStatus: '신고접수',
    approvalStatus: '높음',
    memberStatus: '검토중',
    location: '창작자',
  },
  {
    id: 2,
    nickname: '이후원',
    email: 'supporter@example.com',
    joinDate: '2024-01-08',
    lastActivity: '1시간 전',
    category: '프로젝트 0개',
    fundingAmount: 650_000,
    status: '신규회원',
    accountStatus: '정상',
    level: '일반',
    projectCount: 1,
    totalAmount: 120_000,
    paymentStatus: '신고접수',
    approvalStatus: '높음',
    memberStatus: '검토중',
    location: '후원자',
  },
  {
    id: 3,
    nickname: '박신고',
    email: 'reported@example.com',
    joinDate: '2024-01-05',
    lastActivity: '3시간 전',
    category: '프로젝트 1개',
    fundingAmount: 120_000,
    status: '검토중',
    accountStatus: '신고접수',
    level: '높음',
    projectCount: 1,
    totalAmount: 120_000,
    paymentStatus: '신고접수',
    approvalStatus: '높음',
    memberStatus: '검토중',
    location: '창작자',
  },
  {
    id: 4,
    nickname: '최정지',
    email: 'suspended@example.com',
    joinDate: '2023-12-20',
    lastActivity: '1주일 전',
    category: '프로젝트 0개',
    fundingAmount: 0,
    status: '이용정지',
    accountStatus: '이용정지',
    level: '높음',
    projectCount: 0,
    totalAmount: 120_000,
    paymentStatus: '신고접수',
    approvalStatus: '높음',
    memberStatus: '검토중',
    location: '후원자',
  },
];
